### ISSUE TITLE
Bulk Merge doesn't work

### ISSUE THREAD

**Issue by actforjason** [frangoud/ZoteroDuplicatesMerger#2]
only show

![image](https://user-images.githubusercontent.com/57058325/145555776-60451167-3ac4-4169-b47b-f85075fa03b9.png)

**Comment by ArneVogel** [comment]
I noticed the same problem. Some more information about what happens:

After right clicking and starting the bulk merge the right amount of items to be processed is detected and shown as in actforjason image in the bottom right.
The first duplicate items are selected and in the right panel the date of the earliest is selected. But the items are not getting merged, instead the date keep blinking as if it were unselected and selected repeatedly.

No errors are shown in the output of Zotero.

**Comment by tirzhu** [comment]
Same problem occurred here
This bug is fixed after I change script file _chrome/content/scripts/zoteroduplicatesmerger.js_.
that is:
change line 398 from the following:
  `if (this.mergeSelectedItems(DuplicatesPane, this.selectedItemsList))`
to:
  `if (this.mergeSelectedItems(DuplicatesPane, this.selectedItemsList, true))`

**Comment by HsunGong** [comment]
Thanks to https://github.com/frangoud/ZoteroDuplicatesMerger/issues/2#issuecomment-1002668585 !!!

**Comment by frangoud** [comment]
Sorry for the late reply. And thanks tirzhu for the comment as well. The repo has been updated with the fix as well.
